pipeline 
{
	agent any
    
//    environment { 
//        JenkinsBase = 'jenkins/test/'
//    }
       
	stages { 
		stage('Initialize') 
		{
			
            
			steps {
				timestamps {
					ansiColor('xterm') {
						
						slackSend (color: '#FFFF00', message: "STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
										
						build(job: 'github-comment-label',
		    			parameters:
		    			[
		    				string(name: 'ghprbPullLink', value: "${ghprbPullLink}"), 
			    			string(name: 'LabelCategory', value: "build-${build_type}"),
			    			string(name: 'LabelStatus', value: "PENDING")
			    		],
		    			wait: false, propagate: false)
						
						script {
						
							currentBuild.displayName = "${env.BUILD_NUMBER} - ${build_type} - ${sha_coresoftware}"
							currentBuild.description = "${upstream_build_description} / <a href=\"${git_url_coresoftware}\">coresoftware</a> # ${sha_coresoftware} - ${build_type}" 
							
						}
										
						dir('build')
						{
							deleteDir()
						}	

						dir('coresoftware') {
							deleteDir()
						}
						dir('online_distribution') {
							deleteDir()
						}
						dir('macros')
						{
							deleteDir()
    				}	
						dir('calibrations')
						{
							deleteDir()
    				}	
						dir('tutorials')
						{
							deleteDir()
    				}
						dir('report')
						{
							deleteDir()
    				}
					
						sh('hostname')
						sh('pwd')
						sh('env')
						sh('ls -lvhc')

						dir('utilities/jenkins/built-test/') {
							
							sh('/usr/bin/singularity exec -B /var/lib/jenkins/singularity/cvmfs:/cvmfs -B /gpfs -B /direct -B /afs -B /sphenix /var/lib/jenkins/singularity/cvmfs/sphenix.sdcc.bnl.gov/singularity/rhic_sl7_ext.simg tcsh -f singularity-check.sh')
						
						}
					}
				}
			}
		}

		stage('Git Checkout')
		{
			
			steps 
			{
				timestamps { 
					ansiColor('xterm') {
						
						dir('coresoftware') {
							// git credentialsId: 'sPHENIX-bot', url: 'https://github.com/sPHENIX-Collaboration/coresoftware.git'
							
							checkout(
								[
						 			$class: 'GitSCM',
						   		extensions: [               
							   		[$class: 'CleanCheckout'],     
							     	[
							   			$class: 'PreBuildMerge',
							    		options: [
											mergeRemote: 'origin',
							  			mergeTarget: "$mergeTarget_coresoftware"
							  			]
							    	],
						   		],
							  	branches: [
							    	[name: "${sha_coresoftware}"]
							    ], 
							  	userRemoteConfigs: 
							  	[[
							    	//credentialsId: 'sPHENIX-bot', url: 'https://github.com/sPHENIX-Collaboration/coresoftware.git'
							     	credentialsId: 'sPHENIX-bot', 
							     	url: '${git_url_coresoftware}',
							     	refspec: ('+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/master:refs/remotes/origin/master'), 
							    	branch: ('*')
							  	]]
								] //checkout
							)//checkout
						}
						dir('online_distribution') {
							git credentialsId: 'sPHENIX-bot', url: 'https://github.com/sPHENIX-Collaboration/online_distribution.git'
						}
						//dir('macros')
						//{
						//	git credentialsId: 'sPHENIX-bot', url: 'https://github.com/sPHENIX-Collaboration/macros.git'
    				//}	
						dir('calibrations')
						{
							// git credentialsId: 'sPHENIX-bot', url: 'https://github.com/sPHENIX-Collaboration/calibrations.git'
							
							checkout(
								[
						 			$class: 'GitSCM',
						   		extensions: [               
							   		[$class: 'CleanCheckout'],     
							     	[
							   			$class: 'PreBuildMerge',
							    		options: [
											mergeRemote: 'origin',
							  			mergeTarget: 'master'
							  			]
							    	],
						   		],
							  	branches: [
							    	[name: "${sha_calibrations}"]
							    ], 
							  	userRemoteConfigs: 
							  	[[
							    	//credentialsId: 'sPHENIX-bot', url: 'https://github.com/sPHENIX-Collaboration/coresoftware.git'
							     	credentialsId: 'sPHENIX-bot', 
							     	url: 'https://github.com/sPHENIX-Collaboration/calibrations.git',
							     	refspec: ('+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/master:refs/remotes/origin/master'), 
							    	branch: ('*')
							  	]]
								] //checkout
							)//checkout
							
    				}	
						dir('tutorials')
						{
							git credentialsId: 'sPHENIX-bot', url: 'https://github.com/sPHENIX-Collaboration/tutorials.git'
    				}
					}
				}
			}
		}//stage('SCM Checkout')
		
		// hold this until jenkins supports nested parallel
		//stage('Build')
		//{
		//	parallel {
			
				stage('cpp-check')
				{
					when {
    				// case insensitive regular expression for truthy values
						expression { return run_cppcheck ==~ /(?i)(Y|YES|T|TRUE|ON|RUN)/ }
					}
					steps 
					{
		
		    		build(job: 'cpp-check-pipeline',
		    			parameters:
		    			[
		    				string(name: 'sha_coresoftware', value: "${sha_coresoftware}"), 		    				
		    				string(name: 'git_url_coresoftware', value: "${git_url_coresoftware}"), 		    
		    				string(name: 'mergeTarget_coresoftware', value: "${mergeTarget_coresoftware}"), 		    				
								string(name: 'ghprbPullLink', value: "${ghprbPullLink}"), 
			    			string(name: 'upstream_build_description', value: "${upstream_build_description} / ${env.JOB_NAME}.#${env.BUILD_NUMBER}")
			    		],
		    			wait: false, propagate: false)
		   		}
				}// Stage - cpp check
				 
				
			// hold this until jenkins supports nested parallel 
			//	stage('Build-Test') {
			//		stages{
					    
						stage('sPHENIX-Build')
						{
							
							steps 
							{
								dir('build') {
									deleteDir()
								}
								sh('hostname')
								sh('pwd')
								sh('env')
								sh('ls -lvhc')
										
								sh('/usr/bin/singularity exec -B /var/lib/jenkins/singularity/cvmfs:/cvmfs -B /gpfs -B /direct -B /afs -B /sphenix /var/lib/jenkins/singularity/cvmfs/sphenix.sdcc.bnl.gov/singularity/rhic_sl7_ext.simg tcsh -f utilities/jenkins/built-test/full-build.sh $build_type')
							
							 	script {
							  	build_root_path = pwd();
							 	}
										
								slackSend (color: '#00F000', message: "sPHENIX build available: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL}). Buld available at ${build_root_path}")
							}										
						} // 				stage('sPHENIX-Build')
						
						
						stage('Test')
						{
							parallel {
							
					    
								stage('Build-Analysis')
								{
									
									steps 
									{
										// 	def buildana = scanForIssues tool: gcc4(pattern: 'build/${build_type}/rebuild.log')
        						//	publishIssues issues: [buildana]
        						recordIssues enabledForFailure: true, tool: gcc4(pattern: 'build/${build_type}/rebuild.log')
									}										
								} // 				stage('sPHENIX-Build')
									
							
								stage('test-default')
								{
									
									when {
				    				// case insensitive regular expression for truthy values
										expression { return run_default_test ==~ /(?i)(Y|YES|T|TRUE|ON|RUN)/ }
									}
									steps 
									{
										//sh('/usr/bin/singularity exec -B /var/lib/jenkins/singularity/cvmfs:/cvmfs -B /gpfs -B /direct -B /afs -B /sphenix /var/lib/jenkins/singularity/cvmfs/sphenix.sdcc.bnl.gov/singularity/rhic_sl7_ext.simg tcsh -f utilities/jenkins/built-test/test-default.sh')
												    		
										script
										{
				   						def built = build(job: 'test-default-pipeline',
						    			parameters:
						    			[
							    			string(name: 'build_src', value: "${build_root_path}"), 
							    			string(name: 'sha_macros', value: "${sha_macros}"), 
		    								string(name: 'ghprbPullLink', value: "${ghprbPullLink}"), 
				    						string(name: 'upstream_build_description', value: "${upstream_build_description} / <a href=\"${env.JOB_URL}\">${env.JOB_NAME}</a>.<a href=\"${env.BUILD_URL}\">#${env.BUILD_NUMBER}</a>")
			    						],
						    			wait: true, propagate: true)
						   										
						   				copyArtifacts(projectName: 'test-default-pipeline', selector: specific("${built.number}"));
										}
						   			
						   			dir('macros/macros/g4simulations/')
						   			{
						   				stash name: "test-default-stash", includes: "*"
						   			}
						   			
						   			dir('test-default-output')
						   			{
						   				unstash "test-default-stash"
						   				archiveArtifacts artifacts: '*', onlyIfSuccessful: true	
						   			}
						   				    
									}				
								}
								
								
								stage('test-default-valgrind')
								{
									
									when {
				    				// case insensitive regular expression for truthy values
										expression { return run_default_test ==~ /(?i)(Y|YES|T|TRUE|ON|RUN)/ }
									}
									steps 
									{
										//sh('/usr/bin/singularity exec -B /var/lib/jenkins/singularity/cvmfs:/cvmfs -B /gpfs -B /direct -B /afs -B /sphenix /var/lib/jenkins/singularity/cvmfs/sphenix.sdcc.bnl.gov/singularity/rhic_sl7_ext.simg tcsh -f utilities/jenkins/built-test/test-default.sh')
												    		
										script
										{
				   						def built = build(job: 'test-default-valgrind-pipeline',
						    			parameters:
						    			[
							    			string(name: 'build_src', value: "${build_root_path}"), 
							    			string(name: 'sha_macros', value: "${sha_macros}"), 
		    								string(name: 'ghprbPullLink', value: "${ghprbPullLink}"), 
				    						string(name: 'upstream_build_description', value: "${upstream_build_description} / <a href=\"${env.JOB_URL}\">${env.JOB_NAME}</a>.<a href=\"${env.BUILD_URL}\">#${env.BUILD_NUMBER}</a>")
			    						],
						    			wait: true, propagate: true)
						   										
						   				copyArtifacts(projectName: 'test-default-valgrind-pipeline', selector: specific("${built.number}"));
						   				
										}
						   			
						   			dir('macros/macros/g4simulations/')
						   			{
						   				stash name: "test-default-valgrind-stash", includes: "*"
						   			}
						   			
						   			dir('test-default-valgrind-output')
						   			{
						   				unstash "test-default-valgrind-stash"
						   				archiveArtifacts artifacts: '*', onlyIfSuccessful: true	
						   										   				
											publishValgrind (
							          failBuildOnInvalidReports: false,
							          failBuildOnMissingReports: true,
							          failThresholdDefinitelyLost: '',
							          failThresholdInvalidReadWrite: '1',
							          failThresholdTotal: '',
							          pattern: '*.valgrind.xml',
							          publishResultsForAbortedBuilds: false,
							          publishResultsForFailedBuilds: false,
							          sourceSubstitutionPaths: '',
							          unstableThresholdDefinitelyLost: '',
							          unstableThresholdInvalidReadWrite: '',
							          unstableThresholdTotal: ''
							        )
						   				
						   			}
						   				    
									}				
								}
							
								stage('test-calo-single-qa')
								{
									
									when {
				    				// case insensitive regular expression for truthy values
										expression { return run_calo_qa ==~ /(?i)(Y|YES|T|TRUE|ON|RUN)/ }
									}
									steps 
									{
										script
										{
				   						def built = build(job: 'test-calo-single-qa',
							    			parameters:
							    			[
								    			string(name: 'build_src', value: "${build_root_path}"), 
							    				string(name: 'sha_macros', value: "${sha_macros}"), 
		    									string(name: 'ghprbPullLink', value: "${ghprbPullLink}"), 
				    							string(name: 'upstream_build_description', value: "${upstream_build_description} / <a href=\"${env.JOB_URL}\">${env.JOB_NAME}</a>.<a href=\"${env.BUILD_URL}\">#${env.BUILD_NUMBER}</a>")
			    							],
							    			wait: true, propagate: true)
						   			
						   				copyArtifacts(projectName: 'test-calo-single-qa', selector: specific("${built.number}"));
										}
										archiveArtifacts artifacts: 'qa_page.tar.gz'
										
						    		
										sh('ls -lhv')
						   			
						   			dir('macros/macros/g4simulations/')
						   			{
						   				stash name: "test-calo-single-qa-stash", includes: "*"
						   			}
						   			
						   			dir('test-calo-single-qa-output')
						   			{
						   				unstash "test-calo-single-qa-stash"
						   				archiveArtifacts artifacts: '*', onlyIfSuccessful: true	
						   			}    		   			
						   			
										dir('qa_html')
										{
						    			sh ("tar xzfv ../qa_page.tar.gz")
										}
				
									  publishHTML (target: [
								      allowMissing: false,
								      alwaysLinkToLastBuild: false,
								      keepAll: true,
								      reportDir: 'qa_html',
								      reportFiles: 'index.html',
								      reportName: "Calorimeter QA Report"
								    ])
							   			
									}				
								}// 				stage('test-calo-single-qa')
								
							}// parallel			
						}// stage - Test
		
					//}				//stages("Build-Test")
			//	}				 // stage("Build-Test")
			//} // parallel {
		//}//stage('Build')
		
	}//stages
		
	post {
		always{
		  
			dir('report')
			{
				sh('ls -lvhc')
			  writeFile file: "build-${build_type}.md", text: "* [![Build Status ](https://web.racf.bnl.gov/jenkins-sphenix/buildStatus/icon?job=${env.JOB_NAME}&build=${env.BUILD_NUMBER})](${env.BUILD_URL}) Build with configuration of `${build_type}` [is ${currentBuild.currentResult}](${env.BUILD_URL}), [:bar_chart:Compiler report](${env.BUILD_URL}/gcc4/)"				
			}
		  		  
			archiveArtifacts artifacts: 'report/*.md'
		
			archiveArtifacts artifacts: 'build/${build_type}/rebuild.log'
		}
	
		success {
		
			build(job: 'github-comment-label',
			  parameters:
			  [
					string(name: 'ghprbPullLink', value: "${ghprbPullLink}"), 
					string(name: 'LabelCategory', value: "build-${build_type}"),
					string(name: 'LabelStatus', value: "PASS")
				],
				wait: false, propagate: false)
		
			slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
		}
		failure {
		
			build(job: 'github-comment-label',
			  parameters:
			  [
					string(name: 'ghprbPullLink', value: "${ghprbPullLink}"), 
					string(name: 'LabelCategory', value: "build-${build_type}"),
					string(name: 'LabelStatus', value: "FAIL")
				],
				wait: false, propagate: false)
		
			slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
		}
		unstable {
		
			build(job: 'github-comment-label',
			  parameters:
			  [
					string(name: 'ghprbPullLink', value: "${ghprbPullLink}"), 
					string(name: 'LabelCategory', value: "build-${build_type}"),
					string(name: 'LabelStatus', value: "PASS")
				],
				wait: false, propagate: false)
				
			slackSend (color: '#FFF000', message: "UNSTABLE: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
		}
	}
	
}//pipeline 

